### ISSUE TITLE
Context lost in webpack's watch mode

### ISSUE THREAD

**Issue by ennovum** [michael-ciniawsky/postcss-load-config#105]
The issue is a follow-up of another issue I created in the `postcss-import` repository:
https://github.com/postcss/postcss-import/issues/302

## Problem

In my setup, when I launch webpack in watch mode, the first `postcss` build is fine, but the second and the following builds are broken. It's like the `postcss` config was not there anymore.

## Details

The setup can be found here:
https://github.com/ennovum/kickoff/commit/0671762b7006597b2095a08d38bb4cb0d0edf0f9

@michael-ciniawsky gave me an idea to export a function (instead of an object) from `postcss.config.js`. I did that and logged what happened. I discovered that while rebuilding, my `buildconf` object is modified - the `postcss` section is cleared. I think it's the `postcss-load-config` module that does that. When I export a clone of my `buildconf.postcss` object, the issue is resolved. I don't think it's appropriate for the lib to modify the input object. I shouldn't have to clone it.

What do you think about it?

**Comment by michael-ciniawsky** [comment]
`postcss-load-config` needs to modify the config (`{Object}`) to 'evaluate' it with it's context for dynamic config usage `{Function}`. I'm guessing this is more of a subtile bug between `require` (synchronous) && `postcss-load-config` (asynchronous). Albeit I highly recommend to actually use the `*.config.js` files instead of adding custom config logic on top, this is definitely weird behaviour... Could you try `{Array}` Syntax and check if that

**postcss.config.js**
```js
config.postcss = {
  plugins: [// {Array} Syntax 
     require('postcss-plugin')(...options)
  ]
}
```

works ?

It's definitely mandatory for `postcss.config.js` to modify the config, maybe this module doesn't suit this usecase then and for your config approach passing the postcss config directly as loader options is the better approach.

**webpack.config.js**
```
{
  loader: 'postcss-loader',
  options: {
    ident: 'postcss',
    plugins: [
      require('postcss-plugin')(),
      ...plugins
    ]
  }
}
```

Needs still investigation where the error exactly happens

**Comment by ennovum** [comment]
I did a workaround by cloning the postcss config in the `postcss.config.js` file.
https://github.com/ennovum/kickoff/commit/7823aa69981e4948748f5260167d60cb8ee120f9#diff-b19118abc8e2dbd959e8a14a8c0edcd7

I still think the lib should not mutate the input. I think any lib function should not mutate it's arguments. I don't see how it is `mandatory for postcss.config.js to modify the config`, but I don't know the implementation details. I think it should clone it's input and work on the clone and mutate it if it needs to.
