### ISSUE TITLE
Add `file` in error message

### ISSUE THREAD

**Issue by egoist** [michael-ciniawsky/postcss-load-config#116]
## Problem

For these lines:

https://github.com/michael-ciniawsky/postcss-load-config/blob/348fb5b62fcd01f93cfc768859a82458e093d035/index.js#L63-L67

We won't know what postcss config file it's loading when some error is thrown by either `loadPlugins ` or `loadOptions`. So it's very hard to debug...

## Solution

Add `file` info in error message

**Comment by michael-ciniawsky** [comment]
Good idea I started working on a new major (only dropping theoretical `node >= 0.12` support and a few minor changes) and will include this, but it can take a while since I'm mostly busy with work atm. [postcss-load-plugins #42](https://github.com/michael-ciniawsky/postcss-load-plugins/issues/42) you opened a while ago will also be included there then
